# Generated by Django 6.1 on 2026-08-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='roster_limit',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='team',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Legacy field. MGL economy uses manager tokens.', max_digits=12),
        ),
    ]
