# Generated by Django 6.1 on 2026-08-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_roster_limit_alter_team_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='tokens',
            field=models.DecimalField(decimal_places=2, default=50, help_text='Club transfer budget in MGL tokens. Remains with the club if the manager leaves.', max_digits=8),
        ),
    ]
