# Generated by Django 6.1 on 2026-08-24 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerapplication',
            name='tokens',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
