# Generated by Django 6.1 on 2026-08-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0003_alter_managerapplication_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerapplication',
            name='tokens',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=8),
        ),
    ]
