# Generated by Django 6.1 on 2026-08-25 19:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0001_initial'),
        ('managers', '0003_alter_managerapplication_tokens'),
        ('players', '0004_player_age_player_card_tier_player_released_at'),
        ('teams', '0002_team_roster_limit_alter_team_budget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FixtureReleaseBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('batch_number', models.PositiveSmallIntegerField()),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('is_released', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['batch_number'],
            },
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('RESULTS', 'Results'), ('TRANSFER', 'Transfer'), ('AUCTION', 'Auction'), ('FREE_AGENT', 'Free Agent'), ('REWARD', 'Reward'), ('PRESS', 'Press')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('published', models.BooleanField(default=False)),
                ('discord_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('pack_type', models.CharField(choices=[('GOLD', 'Gold'), ('SILVER', 'Silver'), ('BRONZE', 'Bronze'), ('ELITE', 'Elite'), ('YOUTH', 'Youth')], max_length=10, unique=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=50)),
                ('object_id', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuctionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_requests', to='managers.managerapplication')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_requests', to='players.player')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction_requests_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchweek', models.PositiveIntegerField(default=1)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('lineup_deadline', models.DateTimeField(blank=True, null=True)),
                ('release_batch', models.PositiveSmallIntegerField(default=1)),
                ('is_released', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_fixtures', to='teams.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_fixtures', to='teams.team')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mgl_fixtures', to='leagues.league')),
            ],
            options={
                'ordering': ['matchweek', 'scheduled_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ManagerCareerStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.PositiveIntegerField(default=0)),
                ('draws', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('trophies', models.PositiveIntegerField(default=0)),
                ('league_titles', models.PositiveIntegerField(default=0)),
                ('cup_titles', models.PositiveIntegerField(default=0)),
                ('golden_boots', models.PositiveIntegerField(default=0)),
                ('manager_of_week', models.PositiveIntegerField(default=0)),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='career', to='managers.managerapplication')),
            ],
        ),
        migrations.CreateModel(
            name='MatchSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('fixture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='mgl.fixture')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_match_submissions', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PackOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_openings', to='managers.managerapplication')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='openings', to='mgl.pack')),
            ],
        ),
        migrations.CreateModel(
            name='PackReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pack_rewards', to='teams.team')),
                ('opening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='mgl.packopening')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pack_rewards', to='players.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerOwnershipHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=30)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_ownership_history', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_history', to='players.player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ownership_history', to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='RewardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('reason', models.CharField(max_length=255)),
                ('category', models.CharField(default='OTHER', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fixture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards', to='mgl.fixture')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='managers.managerapplication')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMatchStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(30)])),
                ('shots', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('possession', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100)])),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_stats', to='mgl.matchsubmission')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_stats', to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='GoalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(130)])),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_events', to='players.player')),
                ('team_stats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_events', to='mgl.teammatchstats')),
            ],
        ),
        migrations.CreateModel(
            name='GKSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saves', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gk_saves', to='players.player')),
                ('team_stats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gk_saves', to='mgl.teammatchstats')),
            ],
        ),
        migrations.CreateModel(
            name='DefenderRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('10.0'))])),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defender_ratings', to='players.player')),
                ('team_stats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defender_ratings', to='mgl.teammatchstats')),
            ],
        ),
        migrations.CreateModel(
            name='AssistEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(130)])),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assist_events', to='players.player')),
                ('team_stats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assist_events', to='mgl.teammatchstats')),
            ],
        ),
        migrations.CreateModel(
            name='TeamOfTheWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('formation', models.CharField(default='4-2-3-1', max_length=20)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('week_start',), name='unique_totw_week')],
            },
        ),
        migrations.CreateModel(
            name='TOTWSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=10)),
                ('manager_reward', models.DecimalField(decimal_places=2, default=Decimal('0.20'), max_digits=6)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='totw_selections', to='players.player')),
                ('totw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='mgl.teamoftheweek')),
            ],
        ),
        migrations.CreateModel(
            name='Trophy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('season', models.CharField(blank=True, max_length=50)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trophies', to='managers.managerapplication')),
            ],
        ),
        migrations.CreateModel(
            name='ManagerWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('wins', models.PositiveSmallIntegerField(default=0)),
                ('reward', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=6)),
                ('approved', models.BooleanField(default=False)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_weeks', to='managers.managerapplication')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('week_start', 'manager'), name='unique_manager_week')],
            },
        ),
        migrations.CreateModel(
            name='PressConference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reward', models.DecimalField(decimal_places=2, default=Decimal('0.20'), max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='press_conferences', to='mgl.fixture')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='press_conferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('fixture', 'manager'), name='unique_fixture_manager_press')],
            },
        ),
        migrations.AddConstraint(
            model_name='teammatchstats',
            constraint=models.UniqueConstraint(fields=('submission', 'team'), name='unique_submission_team_stats'),
        ),
        migrations.AddConstraint(
            model_name='gksave',
            constraint=models.UniqueConstraint(fields=('team_stats', 'player'), name='unique_gk_save'),
        ),
        migrations.AddConstraint(
            model_name='defenderrating',
            constraint=models.UniqueConstraint(fields=('team_stats', 'player'), name='unique_defender_rating'),
        ),
        migrations.AddConstraint(
            model_name='totwselection',
            constraint=models.UniqueConstraint(fields=('totw', 'slot'), name='unique_totw_slot'),
        ),
        migrations.AddConstraint(
            model_name='totwselection',
            constraint=models.UniqueConstraint(fields=('totw', 'player'), name='unique_totw_player'),
        ),
    ]
