# Generated by Django 6.1 on 2026-08-28 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0004_manager_tokens_auctions_scouting'),
        ('mgl', '0002_ocm_market'),
        ('players', '0008_player_fc26_attributes'),
        ('teams', '0004_official_sl1_clubs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerClubSpell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_spells', to='managers.managerapplication')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_spells', to='teams.team')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ScoutAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold')], max_length=10)),
                ('level', models.PositiveSmallIntegerField(default=0)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(blank=True, max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ready_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='PENDING', max_length=12)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scout_assignments', to='managers.managerapplication')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scout_assignments', to='players.player')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ScoutProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bronze_level', models.PositiveSmallIntegerField(default=0)),
                ('silver_level', models.PositiveSmallIntegerField(default=0)),
                ('gold_level', models.PositiveSmallIntegerField(default=0)),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scout_profile', to='managers.managerapplication')),
            ],
        ),
        migrations.CreateModel(
            name='ScoutReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(max_length=10)),
                ('level', models.PositiveSmallIntegerField(default=0)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(blank=True, max_length=10)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='mgl.scoutassignment')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scout_reports', to='managers.managerapplication')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scout_reports', to='players.player')),
            ],
            options={
                'ordering': ['-discovered_at'],
            },
        ),
    ]
