# Generated by Django 6.1 on 2026-08-29 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgl', '0005_managerclubspell_end_reason'),
        ('teams', '0004_official_sl1_clubs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pressconference',
            name='unique_fixture_manager_press',
        ),
        migrations.AddField(
            model_name='clubapplication',
            name='discord_username',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='clubapplication',
            name='gamertag',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='clubapplication',
            name='games_per_week',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='clubapplication',
            name='new_gen_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clubapplication',
            name='referred_by',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='pressconference',
            name='category',
            field=models.CharField(default='performance', max_length=40),
        ),
        migrations.AddField(
            model_name='pressconference',
            name='matchweek',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pressconference',
            name='question_key',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='pressconference',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='press_conferences', to='teams.team'),
        ),
        migrations.AddField(
            model_name='pressconference',
            name='trigger',
            field=models.CharField(choices=[('MATCH', 'Match'), ('SIGNING', 'Signing'), ('APPOINTMENT', 'Appointment'), ('ODD_MATCHDAY', 'Odd matchday')], default='MATCH', max_length=20),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='category',
            field=models.CharField(choices=[('RESULTS', 'Results'), ('TRANSFER', 'Transfer'), ('AUCTION', 'Auction'), ('FREE_AGENT', 'Free Agent'), ('REWARD', 'Reward'), ('PRESS', 'Press'), ('MANAGER', 'Manager'), ('SIGNING', 'Signing'), ('SCOUTING', 'Scouting')], max_length=30),
        ),
        migrations.AlterField(
            model_name='pressconference',
            name='fixture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='press_conferences', to='mgl.fixture'),
        ),
        migrations.AddConstraint(
            model_name='pressconference',
            constraint=models.UniqueConstraint(condition=models.Q(('fixture__isnull', False)), fields=('fixture', 'manager'), name='unique_fixture_manager_press'),
        ),
        migrations.AddConstraint(
            model_name='pressconference',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING'), models.Q(('question_key', ''), _negated=True)), fields=('manager', 'question_key'), name='unique_pending_press_question'),
        ),
    ]
