# Generated by Django 6.1 on 2026-08-31 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0004_league_display_fields'),
        ('managers', '0004_manager_tokens_auctions_scouting'),
        ('mgl', '0016_scout_club_and_unique_claims'),
        ('players', '0009_player_dob_playstyles'),
        ('teams', '0006_team_badge_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='season_number',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
        migrations.CreateModel(
            name='HistoricalSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('year_label', models.CharField(blank=True, max_length=32)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('clubs_count', models.PositiveIntegerField(default=0)),
                ('games_played', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('FINALIZED', 'Finalized')], default='ACTIVE', max_length=20)),
                ('is_locked', models.BooleanField(default=False)),
                ('league_winner_name', models.CharField(blank=True, max_length=120)),
                ('cup_winner_name', models.CharField(blank=True, max_length=120)),
                ('manager_of_season_name', models.CharField(blank=True, max_length=120)),
                ('manager_of_season_club', models.CharField(blank=True, max_length=120)),
                ('ballon_dor_name', models.CharField(blank=True, max_length=120)),
                ('top_scorer_name', models.CharField(blank=True, max_length=120)),
                ('top_scorer_goals', models.PositiveIntegerField(blank=True, null=True)),
                ('top_assists_name', models.CharField(blank=True, max_length=120)),
                ('top_assists_count', models.PositiveIntegerField(blank=True, null=True)),
                ('young_player_name', models.CharField(blank=True, max_length=120)),
                ('top_goalkeeper_name', models.CharField(blank=True, max_length=120)),
                ('fair_play_name', models.CharField(blank=True, max_length=120)),
                ('biggest_win_home_name', models.CharField(blank=True, max_length=120)),
                ('biggest_win_away_name', models.CharField(blank=True, max_length=120)),
                ('biggest_win_home_goals', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('biggest_win_away_goals', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('unbeaten_team_name', models.CharField(blank=True, max_length=120)),
                ('unbeaten_games', models.PositiveIntegerField(blank=True, null=True)),
                ('tots_formation', models.CharField(default='4-2-3-1', max_length=20)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('ballon_dor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='season_ballon_dor', to='players.player')),
                ('biggest_win_away', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='season_biggest_win_away', to='teams.team')),
                ('biggest_win_home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='season_biggest_win_home', to='teams.team')),
                ('cup_winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='season_cup_titles', to='teams.team')),
                ('fair_play_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='season_fair_play_awards', to='teams.team')),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_seasons', to=settings.AUTH_USER_MODEL)),
                ('league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historical_seasons', to='leagues.league')),
                ('league_winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='season_league_titles', to='teams.team')),
                ('manager_of_season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='season_manager_awards', to='managers.managerapplication')),
                ('top_assists_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='season_assist_awards', to='players.player')),
                ('top_goalkeeper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='season_gk_awards', to='players.player')),
                ('top_scorer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='season_golden_boots', to='players.player')),
                ('unbeaten_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='season_unbeaten_runs', to='teams.team')),
                ('young_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='season_young_player_awards', to='players.player')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='SeasonTableRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('team_name', models.CharField(max_length=120)),
                ('played', models.PositiveSmallIntegerField(default=0)),
                ('wins', models.PositiveSmallIntegerField(default=0)),
                ('draws', models.PositiveSmallIntegerField(default=0)),
                ('losses', models.PositiveSmallIntegerField(default=0)),
                ('gf', models.PositiveSmallIntegerField(default=0)),
                ('ga', models.PositiveSmallIntegerField(default=0)),
                ('gd', models.SmallIntegerField(default=0)),
                ('points', models.SmallIntegerField(default=0)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_rows', to='mgl.historicalseason')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historical_table_rows', to='teams.team')),
            ],
            options={
                'ordering': ['position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('season', 'position'), name='unique_season_table_position')],
            },
        ),
        migrations.CreateModel(
            name='SeasonTotsPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=12)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('player_name', models.CharField(blank=True, max_length=120)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='season_tots_picks', to='players.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tots_picks', to='mgl.historicalseason')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('season', 'slot'), name='unique_season_tots_slot')],
            },
        ),
    ]
