# Generated by Django 6.1 on 2026-08-31 17:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def mark_existing_official_rows(apps, schema_editor):
    MatchSubmission = apps.get_model("mgl", "MatchSubmission")
    WeeklyAwardBatch = apps.get_model("mgl", "WeeklyAwardBatch")
    MatchSubmission.objects.filter(status="APPROVED").update(stats_applied=True)
    WeeklyAwardBatch.objects.filter(completed=True, status="").update(status="APPROVED")


class Migration(migrations.Migration):


class Migration(migrations.Migration):

    dependencies = [
        ('mgl', '0018_notify_rewards_weekly'),
        ('players', '0009_player_dob_playstyles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='defenderrating',
            name='tackles',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='gksave',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('10.0'))]),
        ),
        migrations.AddField(
            model_name='matchsubmission',
            name='stats_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pressconference',
            name='season_number',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name='weeklyawardbatch',
            name='has_ties',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weeklyawardbatch',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='weeklyawardbatch',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklyawardbatch',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_award_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weeklyawardbatch',
            name='status',
            field=models.CharField(blank=True, choices=[('EMPTY', 'No activity'), ('PENDING_REVIEW', 'Awaiting admin review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='', max_length=20),
        ),
        migrations.CreateModel(
            name='MonthlyAwardBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_start', models.DateField(unique=True)),
                ('notes', models.TextField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[('EMPTY', 'No activity'), ('PENDING_REVIEW', 'Awaiting admin review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='', max_length=20)),
                ('has_ties', models.BooleanField(default=False)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_award_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerMatchRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('1.0')), django.core.validators.MaxValueValidator(Decimal('10.0'))])),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_ratings', to='players.player')),
                ('team_stats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_ratings', to='mgl.teammatchstats')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('team_stats', 'player'), name='unique_player_match_rating')],
            },
        ),
    ]
