# Generated by Django 6.1 on 2026-08-27 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
        ('teams', '0003_ocm_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionbid',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction_bids', to='teams.team'),
        ),
    ]
