# Generated by Django 6.1 on 2026-08-28 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_ocm_market'),
        ('managers', '0004_manager_tokens_auctions_scouting'),
        ('teams', '0004_official_sl1_clubs'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerauction',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='playerauction',
            name='listed_by_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listed_auctions', to='managers.managerapplication'),
        ),
        migrations.AddField(
            model_name='playerauction',
            name='listing_kind',
            field=models.CharField(choices=[('FREE_AGENT', 'Free agent'), ('CLUB', 'Club player')], default='FREE_AGENT', max_length=20),
        ),
        migrations.AddField(
            model_name='playerauction',
            name='origin_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_auctions', to='teams.team'),
        ),
    ]
