"""Press conference question bank. Keys must be unique across categories."""

QUESTION_BANK = {
    "post_match": [
        ("pm_assess", "How do you assess your team's performance today?"),
        ("pm_pleased", "What pleased you most about the performance?"),
        ("pm_improve", "What do you think needs improving?"),
        ("pm_important", "How important was that result?"),
        ("pm_fair", "Was the final score a fair reflection of the match?"),
        ("pm_pressure", "How do you feel your players responded to the pressure?"),
        ("pm_standard", "Was that the standard you demand from this squad?"),
        ("pm_message", "What message does that performance send?"),
        ("pm_character", "What did you learn about the character of this group today?"),
        ("pm_plan", "How closely did the match follow the game plan?"),
        ("pm_energy", "Were you happy with the energy levels throughout the match?"),
        ("pm_second", "How did you feel about the second-half response?"),
        ("pm_control", "Did you feel in control of the contest?"),
        ("pm_details", "Which details decided the match for you?"),
        ("pm_dressing", "How did the dressing room react to that result?"),
    ],
    "win": [
        ("win_key", "What was the key to today's victory?"),
        ("win_impressed", "Who impressed you most today?"),
        ("win_three", "How important was it to get three points?"),
        ("win_expect", "Does this result change your expectations for the season?"),
        ("win_goals", "Your team scored plenty today. What pleased you most?"),
        ("win_belief", "Does a result like that increase belief in the dressing room?"),
        ("win_statement", "Was that a statement performance from your side?"),
        ("win_clinical", "How pleased were you with how clinical the team was?"),
        ("win_together", "How important was the togetherness in that win?"),
        ("win_continue", "Can you keep this level of performance going?"),
        ("win_mentality", "What does this win say about the mentality of the squad?"),
        ("win_bench", "How much did the squad options help you today?"),
    ],
    "draw": [
        ("dr_dropped", "Do you see this as two points dropped or one point gained?"),
        ("dr_different", "What would you have done differently?"),
        ("dr_happy", "Were you happy with your team's performance?"),
        ("dr_late", "Did you feel there was a winner in the game?"),
        ("dr_share", "Is a point a fair outcome from what you saw?"),
        ("dr_frustration", "How much frustration is there after sharing the points?"),
        ("dr_chance", "Did you create enough to win the match?"),
        ("dr_next", "How do you take this result into the next fixture?"),
        ("dr_control", "Where did you lose control of the contest?"),
        ("dr_positives", "What positives do you take from a draw like that?"),
    ],
    "loss": [
        ("ls_wrong", "What went wrong today?"),
        ("ls_respond", "How do you respond after a result like this?"),
        ("ls_change", "What needs to change before the next match?"),
        ("ls_concern", "Are you concerned about the current form?"),
        ("ls_lift", "How do you lift the group after a result like that?"),
        ("ls_honest", "How honest an assessment can you give of that performance?"),
        ("ls_errors", "Were the mistakes individual, or was it a collective issue?"),
        ("ls_learn", "What must the players take from this defeat?"),
        ("ls_reset", "Is it a case of resetting quickly and moving on?"),
        ("ls_standards", "Did the performance fall below your standards?"),
        ("ls_reaction", "How did the players react at full time?"),
        ("ls_fix", "What is the first thing you want to fix on the training pitch?"),
    ],
    "transfers": [
        ("tr_important", "How important is your latest signing?"),
        ("tr_add", "What does this player add to your squad?"),
        ("tr_finished", "Are you finished in the transfer market?"),
        ("tr_qualities", "What qualities attracted you to this player?"),
        ("tr_limit", "How are you balancing the squad with the 30-player limit?"),
        ("tr_happy", "Are you happy with the latest signing?"),
        ("tr_fit", "How quickly do you expect the new signing to fit the system?"),
        ("tr_horizon", "Are you building for immediate success or the long term?"),
        ("tr_more", "Is the recruitment window finished, or are you still looking?"),
        ("tr_need", "Which area of the squad did this signing address?"),
        ("tr_trust", "How much trust will you place in the new arrival straight away?"),
        ("tr_identity", "Does this signing say something about the identity of the club?"),
    ],
    "multiple_signings": [
        ("ms_happy", "You've made several additions recently. Are you happy with the squad now?"),
        ("ms_settling", "How quickly are your new signings settling in?"),
        ("ms_tactical", "Has your recruitment changed your tactical plans?"),
        ("ms_blend", "How do you blend the new players with the existing group?"),
        ("ms_depth", "Do these signings give you the depth you wanted?"),
        ("ms_compete", "Will the new arrivals push the current starters?"),
        ("ms_done", "Is the squad now where you want it, or is there more to do?"),
        ("ms_minutes", "How will you manage minutes across a bigger group?"),
    ],
    "tactics": [
        ("tac_changed", "Has your approach changed recently?"),
        ("tac_formation", "What formation are you looking to build around?"),
        ("tac_midfield", "What do you want your midfield to provide?"),
        ("tac_depth", "How important is squad depth to your plans?"),
        ("tac_press", "How important was the press in today's result?"),
        ("tac_shape", "Did you get the shape you wanted from the first whistle?"),
        ("tac_width", "Did you want more width, or was the compact shape deliberate?"),
        ("tac_opponent", "Were you surprised by your opponent's approach?"),
        ("tac_change", "What tactical change made the difference?"),
        ("tac_ball", "Do you want more control of the ball, or more direct play?"),
        ("tac_defence", "How do you assess the defensive structure?"),
        ("tac_attack", "What is the attacking idea you want supporters to recognise?"),
        ("tac_set", "How much work has gone into set pieces?"),
        ("tac_flex", "How flexible are you prepared to be from game to game?"),
    ],
    "appointment": [
        ("nm_priorities", "What are your first priorities at the club?"),
        ("nm_attracted", "What attracted you to this club?"),
        ("nm_expect", "What can supporters expect from your team?"),
        ("nm_target", "What is your target for the season?"),
        ("nm_philosophy", "How would you describe your football philosophy?"),
        ("nm_squad", "What did you make of the squad you have inherited?"),
        ("nm_start", "How quickly do you want to put your stamp on this club?"),
        ("nm_fans", "What do you want the supporters to see from day one?"),
        ("nm_identity", "What identity do you want {club} to have?"),
        ("nm_first", "You've just taken charge of {club}. What are your first priorities as the new manager?"),
        ("nm_culture", "What kind of culture do you want to build at {club}?"),
        ("nm_time", "How much time do you feel you need to implement your ideas?"),
    ],
    "rivalry": [
        ("rv_important", "How important is this fixture to you?"),
        ("rv_expect", "What do you expect from your opponents?"),
        ("rv_step", "Is this the type of game your players need to step up in?"),
        ("rv_message", "What message does that result send to the rest of the division?"),
        ("rv_respect", "Did you give the opponent enough respect today?"),
        ("rv_edge", "How do you keep an edge in matches like this?"),
        ("rv_occasion", "Do your players thrive on this kind of occasion?"),
        ("rv_history", "How much does the history of this fixture matter to you?"),
        ("rv_focus", "Is it about the occasion, or treating it as another league match?"),
        ("rv_big", "How important was today's result against a league rival?"),
    ],
    "squad": [
        ("sq_impressed", "Which player has impressed you most so far?"),
        ("sq_happy", "Are you happy with your current squad?"),
        ("sq_strengthen", "Where do you believe the squad still needs strengthening?"),
        ("sq_rotation", "How important will squad rotation be?"),
        ("sq_depth", "How important has your squad depth become?"),
        ("sq_minutes", "How are you managing minutes across the squad?"),
        ("sq_young", "How much trust are you placing in the younger players?"),
        ("sq_group", "How is the dressing room looking after that result?"),
        ("sq_leaders", "Who are the leaders in this group?"),
        ("sq_balance", "Do you have the right balance across the pitch?"),
        ("sq_cap", "How are you working within the 30-player squad cap?"),
        ("sq_form", "Which area of the squad is in the best form?"),
    ],
    "season": [
        ("sn_ambitions", "What are your ambitions for the season?"),
        ("sn_end", "Where do you want your club to be by the end of the campaign?"),
        ("sn_rivals", "Who do you see as your biggest rivals?"),
        ("sn_climb", "You're climbing the table. Can you maintain this form?"),
        ("sn_position", "How do you assess the league position after that match?"),
        ("sn_title", "Are you thinking about the top of the table, or taking it game by game?"),
        ("sn_drop", "How do you lift the group after a result like that?"),
        ("sn_patience", "How patient are you prepared to be with this project?"),
        ("sn_points", "What does this result do for your season targets?"),
        ("sn_run", "How important is a consistent run of results from here?"),
        ("sn_belief", "Do you believe this squad can challenge at the top?"),
        ("sn_next", "What is the next milestone for this team?"),
    ],
    "upcoming": [
        ("up_expect", "What are you expecting from your next opponent?"),
        ("up_prepare", "How do you prepare the group for the next fixture?"),
        ("up_focus", "Is the next match a chance to prove a point?"),
        ("up_rotate", "Will you rotate, or keep the same spine?"),
        ("up_recover", "How quickly can the players recover for the next game?"),
        ("up_danger", "Where is the danger in the next fixture?"),
        ("up_same", "Do you change much, or trust the same approach?"),
        ("up_statement", "Can the next match be a statement for your season?"),
    ],
    "form": [
        ("fm_run", "How do you explain the current run of results?"),
        ("fm_confidence", "Where is the confidence level in the squad?"),
        ("fm_momentum", "How do you keep or regain momentum from here?"),
        ("fm_pressure", "Is the pressure starting to tell on the group?"),
        ("fm_consistency", "What is stopping the team from being more consistent?"),
        ("fm_react", "How have the players reacted to recent performances?"),
        ("fm_training", "Has anything changed on the training ground?"),
        ("fm_belief", "Do you still have full belief in this group?"),
    ],
}

MATCH_CATEGORY_BY_RESULT = {
    "WIN": ("win", "post_match", "tactics", "rivalry", "squad", "season"),
    "DRAW": ("draw", "post_match", "tactics", "squad", "upcoming"),
    "LOSS": ("loss", "post_match", "tactics", "season", "form", "squad"),
}

ODD_MATCHDAY_CATEGORIES = ("season", "squad", "tactics", "upcoming", "form", "rivalry")
SIGNING_CATEGORIES = ("transfers",)
MULTI_SIGNING_CATEGORIES = ("multiple_signings", "transfers")
APPOINTMENT_CATEGORIES = ("appointment",)

RECENT_QUESTION_LIMIT = 12
