# Generated by Django 6.1 on 2026-08-24 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fc27_club', models.CharField(blank=True, max_length=100)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(blank=True, choices=[('GK', 'Goalkeeper'), ('CB', 'Centre Back'), ('LB', 'Left Back'), ('RB', 'Right Back'), ('LWB', 'Left Wing Back'), ('RWB', 'Right Wing Back'), ('CDM', 'Defensive Midfielder'), ('CM', 'Central Midfielder'), ('CAM', 'Attacking Midfielder'), ('LM', 'Left Midfielder'), ('RM', 'Right Midfielder'), ('LW', 'Left Winger'), ('RW', 'Right Winger'), ('ST', 'Striker'), ('CF', 'Centre Forward')], max_length=10)),
                ('overall', models.PositiveIntegerField(default=0)),
                ('pace', models.PositiveIntegerField(default=0)),
                ('shooting', models.PositiveIntegerField(default=0)),
                ('passing', models.PositiveIntegerField(default=0)),
                ('dribbling', models.PositiveIntegerField(default=0)),
                ('defending', models.PositiveIntegerField(default=0)),
                ('physical', models.PositiveIntegerField(default=0)),
                ('is_free_agent', models.BooleanField(default=True)),
                ('transfer_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('appearances', models.PositiveIntegerField(default=0)),
                ('goals', models.PositiveIntegerField(default=0)),
                ('assists', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mgl_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='teams.team')),
            ],
        ),
    ]
