# Generated by Django 6.1 on 2026-08-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='fc27_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
