# Generated by Django 6.1 on 2026-08-24 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_fc27_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='transfer_value',
        ),
    ]
