# Generated by Django 6.1 on 2026-08-25 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_player_age_player_card_tier_player_released_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='fc27_club',
        ),
    ]
