# Generated by Django 6.1 on 2026-08-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_remove_player_fc27_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='fc27_club',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
