# Generated by Django 6.1 on 2026-08-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_player_fc26_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='fc_playstyle_plus',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='player',
            name='fc_playstyles',
            field=models.TextField(blank=True),
        ),
    ]
